language: node.js
node_js:
  - '10'
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
  - cd client
  - npm install
script:
  - npm run build
deploy:
  provider: heroku
  api_key:
    secure: 'ScAAd+eYyIWLmSqy6w4gbxQuSUTToPsmrfqqSDGpbOJY4tMMWAqKabl6gj1YcS2CGKvJKObLXhFLBndVJ2bwZsv7f/1BMvF7eM0+uksMuzzhjS5UkMvoK/nt/u/FpfaXYf+MHFuk4kQLsZlj9TMaFYOCMEI79jLsm79RqKK9xvktk5Nsik+FDiHVsI0JN9nx3gGHnK61sjmg5PWjMtiZcTIMYaCHixET9nj49C2D7r7y386xOzzglDZ7w+t7qyJZTzb2dFrq25rAHiaXLNPd5pu0BJGp6qCwg+DxDOKq0YqDCKFPqyDtnYoQZpHygik8UntKGl+tG4s3vOvswzrMduEZ7gSUbgzjkCXaIouOATvbwrPJEFSChkG5mVBOb/sKVb8cGanRBcZkHsGQHZ4Jw9i3TgKJP8LaHlTT+saMnRWfv2/B6q5trZKtYPv//D1fLZRJ7al1VT0mlebtjCipDa5lRKKEbDBJZTyNh1iI1lSpcJF3X7k0DZ8NO9WCnYQpv13nsWMa9aNtyUMAFA7m9fvmWnTeytueYTQlKkSsKrsowrfrol+OmHxyOdVjmKnA6NZ9Fgchfx8MUBgnuasYZ2ExTAZBzjxS2F5CDknucZmrytDFrLozJ2jSohPIA/eXzUKVkjO/8OzszIHpYVywIIrHcZjniAxj3EhhPTOak/o='
  app: react-exam-maker
  on:
    repo: benjaminadk/react-exam-maker
